# Generated by Django 5.0.7 on 2024-09-29 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_birthyear_alter_profile_options_profile_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=uuid.uuid1, max_length=15, unique=True),
        ),
    ]
