# Generated by Django 5.0.7 on 2024-10-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.budgetrange', verbose_name='برای یک کافه رفتن معمولا چه مبلغی را در نظر می\u200cگیرید؟'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.dietarypreference', verbose_name='غذای مورد علاقه شما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hobby', verbose_name='سرگرمی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.job', verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_guests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معمولا با چند نفر می\u200cآیید؟'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photography_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.photographystyle', verbose_name='سبک عکاسی مورد علاقه شما'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_reservation_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.preferredreservationtime', verbose_name='زمان مورد علاقه برای رزرو'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], default='M', max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.state', verbose_name='منطقه'),
        ),
    ]
