# Generated by Django 5.0.7 on 2024-10-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_budget_range_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthyear',
            options={'verbose_name': 'سال تولد', 'verbose_name_plural': 'سال\u200cهای تولد'},
        ),
        migrations.AlterModelOptions(
            name='budgetrange',
            options={'verbose_name': 'محدوده بودجه', 'verbose_name_plural': 'محدوده\u200cهای بودجه'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='dietarypreference',
            options={'verbose_name': 'ترجیحات غذایی', 'verbose_name_plural': 'ترجیحات غذایی'},
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'سرگرمی', 'verbose_name_plural': 'سرگرمی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'شغل', 'verbose_name_plural': 'شغل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='photographystyle',
            options={'verbose_name': 'سبک عکاسی مورد علاقه', 'verbose_name_plural': 'سبک\u200cهای عکاسی مورد علاقه'},
        ),
        migrations.AlterModelOptions(
            name='preferredreservationtime',
            options={'verbose_name': 'زمان رزرو مورد علاقه', 'verbose_name_plural': 'زمان\u200cهای رزرو مورد علاقه'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'منطقه', 'verbose_name_plural': 'مناطق'},
        ),
    ]
