# Generated by Django 5.1.1 on 2024-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_birthyear_options_alter_budgetrange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_month',
            field=models.CharField(choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'آبان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], default='1', max_length=2, verbose_name='ماه تولد'),
        ),
    ]
