# Generated by Django 5.0.7 on 2024-10-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'verbose_name': 'ظرفیت', 'verbose_name_plural': 'ظرفیت ها'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.AlterModelOptions(
            name='saloon',
            options={'verbose_name': 'سالن', 'verbose_name_plural': 'سالن ها'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'میز', 'verbose_name_plural': 'میزها'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'زمان', 'verbose_name_plural': 'زمان ها'},
        ),
    ]
